version: "3.8"

services:
  db:
    image: postgres
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=ft_transcendence
      - POSTGRES_USER=ecole
      - POSTGRES_PASSWORD=super_secret_password
    healthcheck:
      test: "/usr/bin/pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB -h db"
      interval: 5s
      timeout: 10s
      retries: 5
  web:
    build: src/web
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - type: bind
        source: src/web/ft_transcendence
        target: /code
    ports:
      - "3600:8000"
    depends_on:
      db:
        condition: service_healthy
        restart: true
    environment:
      - POSTGRES_DB=ft_transcendence
      - POSTGRES_USER=ecole
      - POSTGRES_PASSWORD=super_secret_password

volumes:
  postgres:
