from django.db import models
from django.conf import settings

class Game(models.Model):
    # default pk : "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY
    name = models.CharField(max_length=50, unique=True)

class GameHistory(models.Model):
    class Meta:
        verbose_name_plural = "game histories"

    game = models.ForeignKey(Game, on_delete=models.CASCADE)
    date = models.DateField(auto_now_add=True)
    length = models.DurationField()
    user1 = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True,
                              related_name="history_user1")
    user2 = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True,
                              related_name="history_user2")
    user1_score = models.IntegerField()
    user2_score = models.IntegerField()
