# Generated by Django 5.0 on 2023-12-26 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='bio',
        ),
    ]
